# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 09:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('content', models.TextField(verbose_name='正文')),
                ('status', models.CharField(choices=[('P', 'PUBLIC'), ('E', 'EDITING'), ('D', 'DELETED'), ('C', 'DELETE-COMPELETLY')], max_length=1, verbose_name='文章状态')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('lasted_modified_time', models.DateTimeField(auto_now=True, verbose_name='最新修改时间')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览数')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('topped', models.BooleanField(default=False, verbose_name='是否置顶')),
            ],
        ),
        migrations.CreateModel(
            name='Bloger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portrait', models.ImageField(default='pic/timg.jpg', upload_to='pic/', verbose_name='头像')),
                ('gender', models.CharField(choices=[('F', 'FEMALE'), ('M', 'MALE')], max_length=5)),
                ('signiture', models.CharField(max_length=100)),
                ('likelist', models.ManyToManyField(blank=True, null=True, related_name='re_likelists', to='zxsite.Bloger', verbose_name='关注列表')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='标签名')),
                ('status', models.CharField(choices=[('L', 'LIVE'), ('D', 'DEAD')], max_length=5)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('related_articles', models.PositiveIntegerField(verbose_name='相关文章数')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zxsite.Bloger', verbose_name='作者'),
        ),
    ]
