# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-15 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zxsite', '0003_article_abstract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.TextField(blank=True, null=True, verbose_name='摘要'),
        ),
    ]
