# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-20 02:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zxsite', '0004_auto_20161215_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(verbose_name='评论内容')),
                ('status', models.CharField(choices=[('L', 'LIVE'), ('D', 'DEAD')], max_length=5, verbose_name='状态')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zxsite.Bloger', verbose_name='评论人')),
            ],
        ),
    ]
