# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-20 02:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zxsite', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='zxsite.Article', verbose_name='相关文章'),
        ),
    ]
